ZoltanCrestBank/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using ZoltanCrestBank.Models;
using System.Net.Http;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;
using Newtonsoft.Json;

namespace ZoltanCrestBank.Controllers
{
    public class HomeController : Controller
    {
        public static int glb;
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult Index()
        {

            var txt = "cribhrrtjkon";
            var userId = User.Identity.GetUserId();
             
            if(userId != null)
            {
                var customerId = db.customers.Where(c => c.ApplicationUserId == userId).First().id;
                glb = customerId;
                ViewBag.CustomerId = customerId;

                //  var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(context.Get<ApplicationDbContext>()));
                var manager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
                //  var manager = new ApplicationUserManager(new UserStore<ApplicationUser>(new ApplicationDbContext()));
      //          var user = manager.FindById(userId);


     //           ViewBag.Pin = user.Pin;

              
            }

            return View();

        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Having trouble? Contact Us!";

            return View();
        }

        //[HttpPost]
        //public ActionResult Contact(string message)
        //{
        //    ViewBag.Message = "Thanks, we got your message";

        //    return View();
        //}


        [HttpPost]
        public ActionResult Contact(string message)
        {

            ViewBag.Message = "Thanks, we got your Message!";
            return PartialView("_ContactPartial");
        }
    }
}

ZoltanCrestBank/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using ZoltanCrestBank.Models;
using ZoltanCrestBank.Services;

namespace ZoltanCrestBank.Controllers
{
    public class MainController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();
        
        // GET: /Main/
        public ActionResult Index()
        {
            db.Configuration.ProxyCreationEnabled = false;
            // db.Dispose();
            var customers = db.customers.Include(c => c.User);

            //  return Json(customers.ToList(), JsonRequestBehavior.AllowGet);
            return View(customers.ToList());
        }



        //public ActionResult Index(int? id)
        //{
        //    db.Configuration.ProxyCreationEnabled = false;
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Customers customers = db.customers.Find(id);
        //    if (customers == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(customers);
        //}

        // GET: /Main/Details/5
        public ActionResult Details(int? id)
        {
            db.Configuration.ProxyCreationEnabled = false;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customers customers = db.customers.Find(id);
            if (customers == null)
            {
                return HttpNotFound();
            }
            return View(customers);
        }

        // GET: /Main/Create
        public ActionResult Create()
        {
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Pin");
            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            var userId = User.Identity.GetUserId();

            try
            {
                foreach (string _formData in collection)
                {
                    ViewData[_formData] = collection[_formData];
                }

                var service = new CustomerService(HttpContext.GetOwinContext().Get<ApplicationDbContext>());

                service.CreateCustomer(ViewData["firstName"].ToString(), ViewData["lastName"].ToString(), userId, decimal.Parse(ViewData["balance"].ToString()));


                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // POST: /Main/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include="id,AccountNumber,firstName,lastName,balance,ApplicationUserId")] Customers customers)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.customers.Add(customers);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Pin", customers.ApplicationUserId);
        //    return View(customers);
        //}

        // GET: /Main/Edit/5
        public ActionResult Edit(int? id)
        {
            //using(ApplicationDbContext db = new ApplicationDbContext())
            //{
            //    return View(db.customers.Where(x => x.id == id).FirstOrDefault());
            //}
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customers customers = db.customers.Find(id);
            if (customers == null)
            {
                return HttpNotFound();
            }
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Pin", customers.ApplicationUserId);
            return View(customers);
        }

        // POST: /Main/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

       [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, Customers customer)
        {
            try
            {
                using(ApplicationDbContext dm = new ApplicationDbContext())
                {
                    dm.Entry(customer).State = EntityState.Modified;
                    dm.SaveChanges();
                }
                return RedirectToAction("index");
            }
            catch
            {
                return View();
            }
        }
        //public ActionResult Edit([Bind(Include="firstName,lastName,balance")] Customers customers)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(customers).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Pin", customers.ApplicationUserId);
        //    return View(customers);
        //}

        // GET: /Main/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customers customers = db.customers.Find(id);
            if (customers == null)
            {
                return HttpNotFound();
            }
            return View(customers);
        }

        // POST: /Main/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Customers customers = db.customers.Find(id);
            db.customers.Remove(customers);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ZoltanCrestBank/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using Microsoft.AspNet.Identity.Owin;
using ZoltanCrestBank.Models;
using Microsoft.AspNet.Identity;

namespace ZoltanCrestBank.Controllers
{
    public class TransactionController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        //
        // GET: /Transaction/
        public ActionResult Index()
        {


            return View();
        }
	}
}

ZoltanCrestBank/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ZoltanCrestBank/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>


<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

<div id="formSection">
    <h3>@ViewBag.Message</h3>
    <form method="post" id="formMethod">
        <textarea name="message" id="message" maxlength="150" data-bind="value:message, valueUpdate: 'input'"></textarea>
        <input type="submit" value="send" />
        <span data-bind="text:charactersRemaining"></span> characters remaining.
    </form>
    <img src="~/Content/image/progress.gif" id="progress" style="display:none"/>
</div>

@section scripts
{
<script src="~/Scripts/knockout-3.4.2.js"></script>

    <script>
        function contactViewModel()
        {
            var self = this;
            self.message = ko.observable('');
            self.charactersRemaining = ko.computed(function () {
                return 150 - self.message().length;
            })
        }
        ko.applyBindings(new contactViewModel());
    </script>

    <script>
    $("#formMethod").submit(function () {
        $("#progress").show();
        $.post('', { message: $("#message").val() }).done(function (response) {
            setTimeout(function () {
                $("#formSection").html(response);
            }, 2000);
        });
        return false;
    });
    </script>
  } 

@*@section scripts{
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
}*@

@*Partaial Page update using Microsoft Unobstructive Ajax

<div id="formsec">

    <h3>@ViewBag.Message</h3>
    @using (Ajax.BeginForm(new AjaxOptions { HttpMethod = "post", InsertionMode = InsertionMode.Replace, UpdateTargetId = "formsec" }))
{
    <textarea name="message">

    </textarea>
    <input type="submit" value="send"  />
}
</div>*@

ZoltanCrestBank/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<div class="row">
    <div class="col-md-6 margin-top-20">
        <a href="#" class="btn btn-primary btn-lg btn-block"><span class="glyphicon glyphicon-circle-arrow-down"></span>Withdrawal</a>
        <a href="#" class="btn btn-primary btn-lg btn-block"><span class="glyphicon glyphicon-flash"></span>Quick Cash #1000</a>
        <a href="@Url.Action("Details","Main",new { id = ViewBag.CustomerId })" class="btn btn-primary btn-lg btn-block"><span class="glyphicon glyphicon-question-sign"></span>Balance Enquiry</a>
    </div>
    <div class="col-md-6 margin-top-20">
        <a href="@Url.Action("Statement","Main", new { id = ViewBag.CustomerId })" class="btn btn-primary btn-lg btn-block"><span class="glyphicon glyphicon-print"></span>Print Statement</a>
        <a href="#" class="btn btn-primary btn-lg btn-block"><span class="glyphicon glyphicon-transfer"></span>Transfer Fund</a>
        <a href="@Url.Action("Deposit", "Transaction", new { customerId = ViewBag.CustomerId })" class="btn btn-primary btn-lg btn-block"><span class="glyphicon glyphicon-circle-arrow-up"></span>Deposit</a>
    </div>
</div>

@ViewBag.Pin

@*<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@

ZoltanCrestBank/Views/Home/_ContactPartial.cshtml
<h3>@ViewBag.Message</h3>
<h4>Did you want to send us another message? <a href="@Url.Action("Contact", "Home")"><span class="glyphicon glyphicon-circle-arrow-down">Click Here</span></a></h4>